#!/bin/python3 

import os 
import subprocess
import math
import numpy

path = "/sys/class/power_supply/BAT0"

status = open(f"{path}/status").readline().replace("\n","")
#capacity = int(open(f"{path}/capacity").readline().replace("\n",""))
calc = float(int(open(f"{path}/charge_now").readline().replace("\n","")) / int(open(f"{path}/charge_full").readline().replace("\n","")))
capacity =100*math.trunc((calc*10000))/10000



status_icons = {"Discharging"  : "🔋"  ,
                "Charging"     : "🔌"  ,
                "Full"         : "⚡"  ,
                "Not charging" : "🔋"  ,
                "Unknown"      : "❔"  }

def warn():
    prompt = "🪫Battery is low , connect the charger "
    subprocess.call(["notify-send", prompt], \
    stdout=open(os.devnull, "w"), stderr=subprocess.STDOUT)


icon = status_icons[status]

if status == "Discharging" and capacity <= 25 : 
    icon = "🪫"
#     warn()

print(f"{icon}{capacity}%")


